# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: GameMaster Unit Test

on:
  push:
    branches: [ "main", "unit-test-github-action" ]
  pull_request:
    branches: [ "main", "unit-test-github-action" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libgles2-mesa-dev
        sudo apt-get install qt6-base-dev
        sudo apt install libxcb-xinerama0
        python -m pip install --upgrade pip
        pip install PyQt6 requests
    - name: Test
      run: python ./src/tests/test.py
