# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: GameMaster Unit Test

on:
  push:
    branches: [ "main", "unit-test-github-action" ]
  pull_request:
    branches: [ "main", "unit-test-github-action" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Qt5/Qt6 (yaqti)
      # You may pin to the exact commit or the version.
      # uses: WillBrennan/yaqti@8182822afd102e931137d71da54f52a13597af8d
      uses: WillBrennan/yaqti@2021.07.29
      with:
        # Qt version to pick 5.15.2 or 6.2.1
        version: 6.2.0
        # install os; linux, windows, or mac
        os: linux
        # what platform are you installing for? desktop, winrt, android, or ios
        platform: desktop
        # what optional Qt modules to install? qtcharts, qtnetworkauth ect...
        modules: debug_info
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libgles2-mesa-dev
        sudo apt install qt6-base-dev-tools
        sudo apt-get -qq install libxcb-xinerama0
        python -m pip install --upgrade pip
        pip install PyQt6 requests
    - name: Test
      run: python ./src/tests/test.py
